# Generated by Django 3.1 on 2020-08-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=180)),
                ('boast_or_roast_choice', models.CharField(choices=[('B', 'Boast'), ('R', 'Roast')], max_length=1)),
            ],
        ),
    ]
