# Generated by Django 3.1 on 2020-08-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghost_post_app', '0002_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vote_total',
            field=models.IntegerField(default=0),
        ),
    ]
