# Generated by Django 3.1 on 2020-08-19 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghost_post_app', '0003_post_vote_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='boast_or_roast_choice',
            field=models.CharField(choices=[('B', 'Boast'), ('R', 'Roast')], max_length=5),
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghost_post_app.post')),
            ],
        ),
    ]
