# Generated by Django 3.1 on 2020-08-19 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghost_post_app', '0004_auto_20200819_1944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
